$lines = Get-Content -Path 'src\TracklogDashboard.tsx'
$newLines = @(
    '                            <div className="space-y-4">',
    '                                <div>',
    '                                    <label className="block text-sm font-medium text-slate-700 dark:text-zinc-300 mb-1">',
    '                                        Contraseña',
    '                                    </label>',
    '                                    <input',
    '                                        type="password"',
    '                                        value={loginPassword}',
    '                                        onChange={(e) => setLoginPassword(e.target.value)}',
    '                                        className="w-full px-4 py-2 bg-slate-100 dark:bg-zinc-800 border border-slate-200 dark:border-zinc-700 rounded-lg focus:outline-none focus:ring-2 focus:ring-blue-500 dark:text-white transition-shadow"',
    '                                        placeholder="••••••••"',
    '                                        autoFocus',
    '                                    />',
    '                                </div>',
    '                                {loginError && (',
    '                                    <p className="text-xs text-red-500 font-medium bg-red-50 dark:bg-red-900/40 p-2 rounded-md">{loginError}</p>',
    '                                )}',
    '                            </div>',
    '                            <div className="mt-6 flex justify-end gap-3">',
    '                                <button',
    '                                    type="button"',
    '                                    onClick={() => setShowLoginModal(false)}',
    '                                    className="px-4 py-2 text-sm font-medium text-slate-600 dark:text-zinc-400 hover:bg-slate-100 dark:hover:bg-zinc-800 rounded-lg transition-colors"',
    '                                >',
    '                                    Cancelar',
    '                                </button>',
    '                                <button',
    '                                    type="submit"',
    '                                    disabled={!loginPassword}',
    '                                    className="px-4 py-2 text-sm font-bold text-white bg-blue-600 hover:bg-blue-700 disabled:opacity-50 disabled:cursor-not-allowed rounded-lg transition-colors flex items-center gap-2 shadow-sm"',
    '                                >',
    '                                    <Unlock className="w-4 h-4" />',
    '                                    Desbloquear',
    '                                </button>',
    '                            </div>'
)
$result = $lines[0..4666] + $newLines + $lines[4684..($lines.Length-1)]
Set-Content -Path 'src\TracklogDashboard.tsx' -Value $result
