// Listado de Flotas para Macro-grupos

export const YANACOCHA_FLEETS = new Set([
    "ABANTO",
    "ACUARIO",
    "AHORRO",
    "ALQUIMAX NORTE",
    "ANITA TOURS",
    "AYS CONTRATISTAS",
    "BUREAU",
    "C. QUINUA",
    "CALERO",
    "CATALAN",
    "CCA",
    "CCQ",
    "CHAVIN",
    "COTRINA",
    "CRUZ NORTE",
    "DIVINO SALVADOR",
    "EMP.SERV.MULT.ARICA",
    "EPSA",
    "ESMERALDA",
    "ESMERALDA CORP",
    "EXTRA",
    "EZEDQUIEL",
    "G&M",
    "GEMA",
    "GENESIS",
    "GRUPO FLORES",
    "GRUPO VILCA",
    "GUERRERO",
    "HORMIGUITAS",
    "HUAMAN",
    "INDUSAN",
    "INKA GOLD",
    "INTEGRAL TRANS",
    "INTERCITY",
    "ITTSA",
    "JAIME RAMIREZ",
    "JHC",
    "JHORDAN",
    "JOES",
    "JUANITA",
    "JUNTOS",
    "KALA",
    "L&C",
    "MAFER",
    "MANTARRAYA",
    "MAX",
    "MINERA YANACOCHA",
    "MINSUR",
    "MOVILIDAD PUMA",
    "MRT",
    "MULTITRAC",
    "MYM",
    "NEGOCIOS MAX",
    "NEW TRANSPORT",
    "NUEVA ESPERANZA",
    "NUMAY",
    "PEREDA",
    "PERUFLOT",
    "PESQUERA DIAMANTE",
    "POLAR",
    "PROSEGUR",
    "QUILCATE",
    "R. AYALA",
    "RENTAEQUIPOS",
    "ROCIO",
    "RODRIGUEZ",
    "ROMERO",
    "ROYAL",
    "SANTA ROSA",
    "SARITA",
    "SECURITAS",
    "SGS",
    "STI",
    "TECNO SANPF",
    "TECNOLDHER",
    "TELECOM",
    "TRANSGROUP CAJAM",
    "VULCO",
    "VYC",
    "YANACOCHA",
    "YANACOCHA SULFURO",
    "YANACOCHA_CAMIONETAS",
    "ZAMINE",
    "ZASAL"
]);

export const REPSOL_FLEETS = new Set([
    "REPSOL",
    "ANCO",
    "ANCO_ANTA",
    "FRACSA",
    "INVERTRANS",
    "SERVOSA",
    "TRANSMI",
    "TRADISA"
]);

// Falta agregar el listado de FLOTAS NO CLIENTES
export const TRACKLOG_INTERNAL_FLEETS = new Set([
    "1.- Prestamo/Soporte",
    "Prestamo Arequipa",
    "Prestamo Cajamarca",
    "Prestamo Espinar",
    "Prestamo Lima",
    "Prestamo Trujillo",
    "2.- En reparación",
    "En reparación",
    "3.- Equipos Nuevos",
    "Equipos Nuevos",
    "4.- Equipos de Segunda (Almacen)",
    "Equipos de Segunda (Almacen)",
    "5.- Averiados_legacy",
    "Averiados_legacy",
    "6.- MAO",
    "MAO",
    "INACTIVO",
    "Default Fleet",
    "IBEROAMERICANO_INACTIVO"
]);
